name: Check Pull Request

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "master"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - name: Check style
        run: npm run format-check
      - name: Lint
        run: npm run lint
